using System.Text;
using Microsoft.OpenApi.Models;
using Microsoft.Extensions.Logging;

namespace Bipins.AI.Agents.Tools.CodeGen;

/// <summary>
/// Generates C# model/DTO classes from OpenAPI schemas.
/// </summary>
public class ModelGenerator : IModelGenerator
{
    private readonly ILogger<ModelGenerator> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="ModelGenerator"/> class.
    /// </summary>
    public ModelGenerator(ILogger<ModelGenerator> logger)
    {
        _logger = logger;
    }

    /// <inheritdoc />
    public Task<List<GeneratedFile>> GenerateAsync(
        OpenApiDocument document,
        string namespaceName,
        GeneratorOptions options,
        CancellationToken cancellationToken = default)
    {
        var files = new List<GeneratedFile>();

        if (document.Components?.Schemas == null || document.Components.Schemas.Count == 0)
        {
            _logger.LogWarning("No schemas found in OpenAPI document");
            return Task.FromResult(files);
        }

        _logger.LogInformation("Generating {Count} model classes", document.Components.Schemas.Count);

        foreach (var schema in document.Components.Schemas)
        {
            try
            {
                var code = GenerateModelClass(
                    schema.Key,
                    schema.Value,
                    namespaceName,
                    options);

                files.Add(new GeneratedFile(
                    Path: $"Models/{schema.Key}.cs",
                    Content: code,
                    Description: $"Model class for {schema.Key}"));

                _logger.LogDebug("Generated model class for {SchemaName}", schema.Key);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error generating model for schema {SchemaName}", schema.Key);
            }
        }

        _logger.LogInformation("Successfully generated {Count} model files", files.Count);
        return Task.FromResult(files);
    }

    private string GenerateModelClass(
        string className,
        OpenApiSchema schema,
        string namespaceName,
        GeneratorOptions options)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Generated by Bipins.AI Swagger Client Generator at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// Do not modify this file manually");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {namespaceName}.Models;");
        sb.AppendLine();

        // Using statements
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();

        // XML documentation
        if (options.IncludeXmlDocs)
        {
            sb.AppendLine("/// <summary>");
            if (!string.IsNullOrEmpty(schema.Description))
            {
                sb.AppendLine($"/// {EscapeXmlComment(schema.Description)}");
            }
            else
            {
                sb.AppendLine($"/// Represents a {className}.");
            }
            sb.AppendLine("/// </summary>");
        }

        // Class declaration (using record for immutability)
        sb.AppendLine($"public record {className}");
        sb.AppendLine("{");

        // Properties
        if (schema.Properties != null && schema.Properties.Count > 0)
        {
            var propertyIndex = 0;
            foreach (var property in schema.Properties)
            {
                if (propertyIndex > 0)
                    sb.AppendLine();

                var propertyName = TypeMapper.ToPascalCase(property.Key);
                var propertyType = TypeMapper.MapToCSharpType(property.Value, options.UseNullableReferenceTypes);
                var isRequired = schema.Required?.Contains(property.Key) ?? false;

                // XML documentation
                if (options.IncludeXmlDocs)
                {
                    sb.AppendLine("    /// <summary>");
                    if (!string.IsNullOrEmpty(property.Value.Description))
                    {
                        sb.AppendLine($"    /// {EscapeXmlComment(property.Value.Description)}");
                    }
                    else
                    {
                        sb.AppendLine($"    /// Gets or sets the {propertyName}.");
                    }
                    sb.AppendLine("    /// </summary>");
                }

                // JsonPropertyName attribute
                sb.AppendLine($"    [JsonPropertyName(\"{property.Key}\")]");

                // Property declaration
                var defaultValue = isRequired && !propertyType.EndsWith("?") ? " = default!;" : ";";
                sb.AppendLine($"    public {propertyType} {propertyName} {{ get; init; }}{defaultValue}");

                propertyIndex++;
            }
        }
        else
        {
            sb.AppendLine("    // No properties defined in schema");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeXmlComment(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;

        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&apos;");
    }
}
